stages:
  fill_na:
      cmd: python scripts/data_scripts/fill_na.py data/raw/SF_Mandarin_dataset_ver3_csv.csv
      deps:
        - data/raw/SF_Mandarin_dataset_ver3_csv.csv
        - scripts/data_scripts/fill_na.py
        - scripts/data_scripts/data_methods.py
      outs:
        - data/stage_fill_na

  data_prepare:
    cmd: python scripts/data_scripts/data_prepare.py data/stage_fill_na/dataset.csv
    deps:
      - data/stage_fill_na/dataset.csv
      - scripts/data_scripts/data_prepare.py
      - scripts/data_scripts/data_methods.py
    outs:
      - data/stage_data_prepare

  fix_errors:
    cmd: python scripts/data_scripts/fix_errors.py data/stage_data_prepare/dataset.csv
    deps:
      - data/stage_data_prepare/dataset.csv
      - scripts/data_scripts/fix_errors.py
      - scripts/data_scripts/data_methods.py
    outs:
      - data/stage_fix_errors

#  create_features:
#    cmd: python3 scripts/data_scripts/create_features.py data/stage_fix_errors/dataset.csv
#    deps:
#    - data/stage_fix_errors/dataset.csv
#    - scripts/data_scripts/create_features.py
#    - scripts/data_scripts/data_methods.py
#    outs:
#    - data/stage_create_features

#  train_test_split:
#    cmd: python3 scripts/data_scripts/train_test_split.py data/stage_create_features/dataset.csv
#    deps:
#    - data/stage_create_features/dataset.csv
#    - scripts/data_scripts/train_test_split.py
#    params:
#    - split.split_ratio
#    outs:
#    - data/stage_train_test_split

  train_dec_tree:
    cmd: python scripts/model_scripts/dt.py data/stage_train_test_split/train_${bank.bank_id}.csv
    deps:
      - data/stage_train_test_split/train_${bank.bank_id}.csv
      - scripts/model_scripts/dt.py
    params:
      - tree.max_depth
      - bank.bank_id
    outs:
      - models/model_tree_${bank.bank_id}.pkl

  evaluate_dec_tree:
    cmd: python scripts/model_scripts/evaluate.py data/stage_train_test_split/test_${bank.bank_id}.csv models/model_tree_${bank.bank_id}.pkl score_dec_tree_${bank.bank_id}.json
    deps:
      - data/stage_train_test_split/test_${bank.bank_id}.csv
      - models/model_tree_${bank.bank_id}.pkl
      - scripts/model_scripts/evaluate.py
    params:
      - bank.bank_id
    metrics:
    - evaluate/score_dec_tree_${bank.bank_id}.json:
        cache: true

  train_log_reg:
    cmd: python scripts/model_scripts/logistic_regression.py data/stage_train_test_split/train_${bank.bank_id}.csv
    deps:
      - data/stage_train_test_split/train_${bank.bank_id}.csv
      - scripts/model_scripts/logistic_regression.py
    params:
      - log_reg.max_depth
      - log_reg.treshold
      - bank.bank_id
    outs:
      - models/model_log_${bank.bank_id}.pkl

  evaluate_log_reg:
    cmd: python scripts/model_scripts/evaluate.py data/stage_train_test_split/test_${bank.bank_id}.csv models/model_log_${bank.bank_id}.pkl score_log_${bank.bank_id}.json
    deps:
      - data/stage_train_test_split/test_${bank.bank_id}.csv
      - models/model_log_${bank.bank_id}.pkl
      - scripts/model_scripts/evaluate.py
    params:
      - bank.bank_id
    metrics:
    - evaluate/score_log_${bank.bank_id}.json:
        cache: true

  train_neur_net:
    cmd: python scripts/model_scripts/neural_network.py data/stage_train_test_split/train_${bank.bank_id}.csv
    deps:
      - data/stage_train_test_split/train_${bank.bank_id}.csv
      - scripts/model_scripts/neural_network.py
    params:
      - neural.max_depth
      - neural.learning_rate_init
      - neural.verbose
      - neural.hidden_layer_sizes_x
      - neural.hidden_layer_sizes_y
      - bank.bank_id
    outs:
      - models/model_net_${bank.bank_id}.pkl

  evaluate_neur_net:
    cmd: python scripts/model_scripts/evaluate.py data/stage_train_test_split/test_${bank.bank_id}.csv models/model_net_${bank.bank_id}.pkl score_net_${bank.bank_id}.json
    deps:
      - data/stage_train_test_split/test_${bank.bank_id}.csv
      - models/model_net_${bank.bank_id}.pkl
      - scripts/model_scripts/evaluate.py
    params:
      - bank.bank_id
    metrics:
    - evaluate/score_net_${bank.bank_id}.json:
        cache: true