stages:
  fill_na:
      cmd: python -m scripts.data_scripts.fill_na data/raw/SF_Mandarin_dataset_ver3_csv.csv
      deps:
        - data/raw/SF_Mandarin_dataset_ver3_csv.csv
        - scripts/data_scripts/fill_na.py
        - scripts/data_scripts/data_methods.py
      outs:
        - data/stage_fill_na/dataset.csv

  data_prepare:
    cmd: python -m scripts.data_scripts.data_prepare data/stage_fill_na/dataset.csv
    deps:
      - data/stage_fill_na/dataset.csv
      - scripts/data_scripts/data_prepare.py
      - scripts/data_scripts/data_methods.py
      - scripts/data_scripts/fill_na.py
    outs:
      - data/stage_data_prepare/dataset.csv

  fix_errors:
    cmd: python -m scripts.data_scripts.fix_errors data/stage_data_prepare/dataset.csv
    deps:
      - data/stage_data_prepare/dataset.csv
      - scripts/data_scripts/fix_errors.py
      - scripts/data_scripts/data_methods.py
      - scripts/data_scripts/utils/seniority_cats.py
      - scripts/data_scripts/fill_na.py
      - scripts/data_scripts/data_prepare.py
    outs:
      - data/stage_fix_errors/dataset.csv

  create_features:
    cmd: python -m scripts.data_scripts.create_features data/stage_fix_errors/dataset.csv
    deps:
    - data/stage_fix_errors/dataset.csv
    - scripts/data_scripts/create_features.py
    - scripts/data_scripts/data_methods.py
    - scripts/data_scripts/utils/seniority_cats.py
    - scripts/data_scripts/fill_na.py
    - scripts/data_scripts/data_prepare.py
    - scripts/data_scripts/fix_errors.py
    outs:
    - data/stage_create_features/dataset.csv

  feature_prepare_A:
    cmd: python -m scripts.data_scripts.feature_prepare A data/stage_create_features/dataset.csv
    deps:
      - data/stage_create_features/dataset.csv
      - scripts/data_scripts/create_features.py
      - scripts/data_scripts/feature_prepare.py
      - scripts/data_scripts/fill_na.py
      - scripts/data_scripts/data_prepare.py
      - scripts/data_scripts/fix_errors.py
      - scripts/data_scripts/utils/seniority_cats.py
      - scripts/data_scripts/data_methods.py
    outs:
      - data/stage_feature_prepare/dataset_A.csv
      - models/scaler_A.pkl

  feature_prepare_B:
    cmd: python -m scripts.data_scripts.feature_prepare B data/stage_create_features/dataset.csv
    deps:
      - data/stage_create_features/dataset.csv
      - scripts/data_scripts/create_features.py
      - scripts/data_scripts/feature_prepare.py
      - scripts/data_scripts/fill_na.py
      - scripts/data_scripts/data_prepare.py
      - scripts/data_scripts/fix_errors.py
      - scripts/data_scripts/utils/seniority_cats.py
      - scripts/data_scripts/data_methods.py
    outs:
      - data/stage_feature_prepare/dataset_B.csv
      - models/scaler_B.pkl

  feature_prepare_C:
    cmd: python -m scripts.data_scripts.feature_prepare C data/stage_create_features/dataset.csv
    deps:
      - data/stage_create_features/dataset.csv
      - scripts/data_scripts/create_features.py
      - scripts/data_scripts/feature_prepare.py
      - scripts/data_scripts/fill_na.py
      - scripts/data_scripts/data_prepare.py
      - scripts/data_scripts/fix_errors.py
      - scripts/data_scripts/utils/seniority_cats.py
      - scripts/data_scripts/data_methods.py
    outs:
      - data/stage_feature_prepare/dataset_C.csv
      - models/scaler_C.pkl

  feature_prepare_D:
    cmd: python -m scripts.data_scripts.feature_prepare D data/stage_create_features/dataset.csv
    deps:
      - data/stage_create_features/dataset.csv
      - scripts/data_scripts/create_features.py
      - scripts/data_scripts/feature_prepare.py
      - scripts/data_scripts/fill_na.py
      - scripts/data_scripts/data_prepare.py
      - scripts/data_scripts/fix_errors.py
      - scripts/data_scripts/utils/seniority_cats.py
      - scripts/data_scripts/data_methods.py
    outs:
      - data/stage_feature_prepare/dataset_D.csv
      - models/scaler_D.pkl

  feature_prepare_E:
    cmd: python -m scripts.data_scripts.feature_prepare E data/stage_create_features/dataset.csv
    deps:
      - data/stage_create_features/dataset.csv
      - scripts/data_scripts/create_features.py
      - scripts/data_scripts/feature_prepare.py
      - scripts/data_scripts/fill_na.py
      - scripts/data_scripts/data_prepare.py
      - scripts/data_scripts/fix_errors.py
      - scripts/data_scripts/utils/seniority_cats.py
      - scripts/data_scripts/data_methods.py
    outs:
      - data/stage_feature_prepare/dataset_E.csv
      - models/scaler_E.pkl

  train_test_split_A:
    cmd: python -m scripts.data_scripts.train_test_split A data/stage_feature_prepare/dataset_A.csv
    deps:
    - data/stage_feature_prepare/dataset_A.csv
    - scripts/data_scripts/train_test_split.py
    - scripts/data_scripts/feature_prepare.py
    - scripts/data_scripts/fill_na.py
    - scripts/data_scripts/data_prepare.py
    - scripts/data_scripts/fix_errors.py
    - scripts/data_scripts/utils/seniority_cats.py
    - scripts/data_scripts/data_methods.py
    - scripts/data_scripts/create_features.py
    params:
    - split.split_ratio
    outs:
    - data/stage_train_test_split/train_A.csv
    - data/stage_train_test_split/test_A.csv

  train_test_split_B:
    cmd: python -m scripts.data_scripts.train_test_split B data/stage_feature_prepare/dataset_B.csv
    deps:
    - data/stage_feature_prepare/dataset_B.csv
    - scripts/data_scripts/train_test_split.py
    - scripts/data_scripts/feature_prepare.py
    - scripts/data_scripts/fill_na.py
    - scripts/data_scripts/data_prepare.py
    - scripts/data_scripts/fix_errors.py
    - scripts/data_scripts/utils/seniority_cats.py
    - scripts/data_scripts/data_methods.py
    - scripts/data_scripts/create_features.py
    params:
    - split.split_ratio
    outs:
    - data/stage_train_test_split/train_B.csv
    - data/stage_train_test_split/test_B.csv

  train_test_split_C:
    cmd: python -m scripts.data_scripts.train_test_split C data/stage_feature_prepare/dataset_C.csv
    deps:
    - data/stage_feature_prepare/dataset_C.csv
    - scripts/data_scripts/train_test_split.py
    - scripts/data_scripts/feature_prepare.py
    - scripts/data_scripts/fill_na.py
    - scripts/data_scripts/data_prepare.py
    - scripts/data_scripts/fix_errors.py
    - scripts/data_scripts/utils/seniority_cats.py
    - scripts/data_scripts/data_methods.py
    - scripts/data_scripts/create_features.py
    params:
    - split.split_ratio
    outs:
    - data/stage_train_test_split/train_C.csv
    - data/stage_train_test_split/test_C.csv

  train_test_split_D:
    cmd: python -m scripts.data_scripts.train_test_split D data/stage_feature_prepare/dataset_D.csv
    deps:
    - data/stage_feature_prepare/dataset_D.csv
    - scripts/data_scripts/train_test_split.py
    - scripts/data_scripts/feature_prepare.py
    - scripts/data_scripts/fill_na.py
    - scripts/data_scripts/data_prepare.py
    - scripts/data_scripts/fix_errors.py
    - scripts/data_scripts/utils/seniority_cats.py
    - scripts/data_scripts/data_methods.py
    - scripts/data_scripts/create_features.py
    params:
    - split.split_ratio
    outs:
    - data/stage_train_test_split/train_D.csv
    - data/stage_train_test_split/test_D.csv

  train_test_split_E:
    cmd: python -m scripts.data_scripts.train_test_split E data/stage_feature_prepare/dataset_E.csv
    deps:
    - data/stage_feature_prepare/dataset_E.csv
    - scripts/data_scripts/train_test_split.py
    - scripts/data_scripts/feature_prepare.py
    - scripts/data_scripts/fill_na.py
    - scripts/data_scripts/data_prepare.py
    - scripts/data_scripts/fix_errors.py
    - scripts/data_scripts/utils/seniority_cats.py
    - scripts/data_scripts/data_methods.py
    - scripts/data_scripts/create_features.py
    params:
    - split.split_ratio
    outs:
    - data/stage_train_test_split/train_E.csv
    - data/stage_train_test_split/test_E.csv

  train_A:
    cmd: python -m scripts.model_scripts.${general.train_method} A data/stage_train_test_split/train_A.csv
    deps:
      - data/stage_train_test_split/train_A.csv
      - scripts/model_scripts/${general.train_method}.py
      - scripts/model_scripts/train.py
      - scripts/data_scripts/train_test_split.py
      - scripts/data_scripts/feature_prepare.py
      - scripts/data_scripts/fill_na.py
      - scripts/data_scripts/data_prepare.py
      - scripts/data_scripts/fix_errors.py
      - scripts/data_scripts/utils/seniority_cats.py
      - scripts/data_scripts/data_methods.py
      - scripts/data_scripts/create_features.py
    params:
      - general.train_method
      - tree.max_depth
      - tree.n_estimators
      - tree.eta
      - tree.reg_lambda
      - tree.reg_alpha
      - tree.scale_pos_weight
      - log_reg.max_iter
      - neural.max_depth
      - neural.learning_rate_init
      - neural.verbose
      - neural.hidden_layer_sizes_x
      - neural.hidden_layer_sizes_y
    outs:
      - models/model_${general.train_method}_A.pkl

  evaluate_A:
    cmd: python -m scripts.model_scripts.evaluate A data/stage_train_test_split/test_A.csv model_${general.train_method}_A.pkl score_${general.train_method}_A.json
    deps:
      - data/stage_train_test_split/test_A.csv
      - models/model_${general.train_method}_A.pkl
      - scripts/model_scripts/evaluate.py
      - scripts/model_scripts/${general.train_method}.py
      - scripts/model_scripts/train.py
      - scripts/data_scripts/train_test_split.py
      - scripts/data_scripts/feature_prepare.py
      - scripts/data_scripts/fill_na.py
      - scripts/data_scripts/data_prepare.py
      - scripts/data_scripts/fix_errors.py
      - scripts/data_scripts/utils/seniority_cats.py
      - scripts/data_scripts/data_methods.py
      - scripts/data_scripts/create_features.py
    params:
      - general.train_method
    metrics:
      - evaluate/score_${general.train_method}_A.json:
          cache: true

  train_B:
    cmd: python -m scripts.model_scripts.${general.train_method} B data/stage_train_test_split/train_B.csv
    deps:
      - data/stage_train_test_split/train_B.csv
      - scripts/model_scripts/${general.train_method}.py
      - scripts/model_scripts/train.py
      - scripts/data_scripts/train_test_split.py
      - scripts/data_scripts/feature_prepare.py
      - scripts/data_scripts/fill_na.py
      - scripts/data_scripts/data_prepare.py
      - scripts/data_scripts/fix_errors.py
      - scripts/data_scripts/utils/seniority_cats.py
      - scripts/data_scripts/data_methods.py
      - scripts/data_scripts/create_features.py
    params:
      - general.train_method
      - tree.max_depth
      - tree.n_estimators
      - tree.eta
      - tree.reg_lambda
      - tree.reg_alpha
      - tree.scale_pos_weight
      - log_reg.max_iter
      - neural.max_depth
      - neural.learning_rate_init
      - neural.verbose
      - neural.hidden_layer_sizes_x
      - neural.hidden_layer_sizes_y
    outs:
      - models/model_${general.train_method}_B.pkl

  evaluate_B:
    cmd: python -m scripts.model_scripts.evaluate B data/stage_train_test_split/test_B.csv model_${general.train_method}_B.pkl score_${general.train_method}_B.json
    deps:
      - data/stage_train_test_split/test_B.csv
      - models/model_${general.train_method}_B.pkl
      - scripts/model_scripts/evaluate.py
      - scripts/model_scripts/${general.train_method}.py
      - scripts/model_scripts/train.py
      - scripts/data_scripts/train_test_split.py
      - scripts/data_scripts/feature_prepare.py
      - scripts/data_scripts/fill_na.py
      - scripts/data_scripts/data_prepare.py
      - scripts/data_scripts/fix_errors.py
      - scripts/data_scripts/utils/seniority_cats.py
      - scripts/data_scripts/data_methods.py
      - scripts/data_scripts/create_features.py
    params:
      - general.train_method
    metrics:
      - evaluate/score_${general.train_method}_B.json:
          cache: true

  train_C:
    cmd: python -m scripts.model_scripts.${general.train_method} C data/stage_train_test_split/train_C.csv
    deps:
      - data/stage_train_test_split/train_C.csv
      - scripts/model_scripts/${general.train_method}.py
      - scripts/model_scripts/train.py
      - scripts/data_scripts/train_test_split.py
      - scripts/data_scripts/feature_prepare.py
      - scripts/data_scripts/fill_na.py
      - scripts/data_scripts/data_prepare.py
      - scripts/data_scripts/fix_errors.py
      - scripts/data_scripts/utils/seniority_cats.py
      - scripts/data_scripts/data_methods.py
      - scripts/data_scripts/create_features.py
    params:
      - general.train_method
      - tree.max_depth
      - tree.n_estimators
      - tree.eta
      - tree.reg_lambda
      - tree.reg_alpha
      - tree.scale_pos_weight
      - log_reg.max_iter
      - neural.max_depth
      - neural.learning_rate_init
      - neural.verbose
      - neural.hidden_layer_sizes_x
      - neural.hidden_layer_sizes_y
    outs:
      - models/model_${general.train_method}_C.pkl

  evaluate_C:
    cmd: python -m scripts.model_scripts.evaluate C data/stage_train_test_split/test_C.csv model_${general.train_method}_C.pkl score_${general.train_method}_C.json
    deps:
      - data/stage_train_test_split/test_C.csv
      - models/model_${general.train_method}_C.pkl
      - scripts/model_scripts/evaluate.py
      - scripts/model_scripts/${general.train_method}.py
      - scripts/model_scripts/train.py
      - scripts/data_scripts/train_test_split.py
      - scripts/data_scripts/feature_prepare.py
      - scripts/data_scripts/fill_na.py
      - scripts/data_scripts/data_prepare.py
      - scripts/data_scripts/fix_errors.py
      - scripts/data_scripts/utils/seniority_cats.py
      - scripts/data_scripts/data_methods.py
      - scripts/data_scripts/create_features.py
    params:
      - general.train_method
    metrics:
      - evaluate/score_${general.train_method}_C.json:
          cache: true

  train_D:
    cmd: python -m scripts.model_scripts.${general.train_method} D data/stage_train_test_split/train_D.csv
    deps:
      - data/stage_train_test_split/train_D.csv
      - scripts/model_scripts/${general.train_method}.py
      - scripts/model_scripts/train.py
      - scripts/data_scripts/train_test_split.py
      - scripts/data_scripts/feature_prepare.py
      - scripts/data_scripts/fill_na.py
      - scripts/data_scripts/data_prepare.py
      - scripts/data_scripts/fix_errors.py
      - scripts/data_scripts/utils/seniority_cats.py
      - scripts/data_scripts/data_methods.py
      - scripts/data_scripts/create_features.py
    params:
      - general.train_method
      - tree.max_depth
      - tree.n_estimators
      - tree.eta
      - tree.reg_lambda
      - tree.reg_alpha
      - tree.scale_pos_weight
      - log_reg.max_iter
      - neural.max_depth
      - neural.learning_rate_init
      - neural.verbose
      - neural.hidden_layer_sizes_x
      - neural.hidden_layer_sizes_y
    outs:
      - models/model_${general.train_method}_D.pkl

  evaluate_D:
    cmd: python -m scripts.model_scripts.evaluate D data/stage_train_test_split/test_D.csv model_${general.train_method}_D.pkl score_${general.train_method}_D.json
    deps:
      - data/stage_train_test_split/test_D.csv
      - models/model_${general.train_method}_D.pkl
      - scripts/model_scripts/evaluate.py
      - scripts/model_scripts/${general.train_method}.py
      - scripts/model_scripts/train.py
      - scripts/data_scripts/train_test_split.py
      - scripts/data_scripts/feature_prepare.py
      - scripts/data_scripts/fill_na.py
      - scripts/data_scripts/data_prepare.py
      - scripts/data_scripts/fix_errors.py
      - scripts/data_scripts/utils/seniority_cats.py
      - scripts/data_scripts/data_methods.py
      - scripts/data_scripts/create_features.py
    params:
      - general.train_method
    metrics:
      - evaluate/score_${general.train_method}_D.json:
          cache: true

  train_E:
    cmd: python -m scripts.model_scripts.${general.train_method} E data/stage_train_test_split/train_E.csv
    deps:
      - data/stage_train_test_split/train_E.csv
      - scripts/model_scripts/${general.train_method}.py
      - scripts/model_scripts/train.py
      - scripts/data_scripts/train_test_split.py
      - scripts/data_scripts/feature_prepare.py
      - scripts/data_scripts/fill_na.py
      - scripts/data_scripts/data_prepare.py
      - scripts/data_scripts/fix_errors.py
      - scripts/data_scripts/utils/seniority_cats.py
      - scripts/data_scripts/data_methods.py
      - scripts/data_scripts/create_features.py
    params:
      - general.train_method
      - tree.max_depth
      - tree.n_estimators
      - tree.eta
      - tree.reg_lambda
      - tree.reg_alpha
      - tree.scale_pos_weight
      - log_reg.max_iter
      - neural.max_depth
      - neural.learning_rate_init
      - neural.verbose
      - neural.hidden_layer_sizes_x
      - neural.hidden_layer_sizes_y
    outs:
      - models/model_${general.train_method}_E.pkl

  evaluate_E:
    cmd: python -m scripts.model_scripts.evaluate E data/stage_train_test_split/test_E.csv model_${general.train_method}_E.pkl score_${general.train_method}_E.json
    deps:
      - data/stage_train_test_split/test_E.csv
      - models/model_${general.train_method}_E.pkl
      - scripts/model_scripts/evaluate.py
      - scripts/model_scripts/${general.train_method}.py
      - scripts/model_scripts/train.py
      - scripts/data_scripts/train_test_split.py
      - scripts/data_scripts/feature_prepare.py
      - scripts/data_scripts/fill_na.py
      - scripts/data_scripts/data_prepare.py
      - scripts/data_scripts/fix_errors.py
      - scripts/data_scripts/utils/seniority_cats.py
      - scripts/data_scripts/data_methods.py
      - scripts/data_scripts/create_features.py
    params:
      - general.train_method
    metrics:
      - evaluate/score_${general.train_method}_E.json:
          cache: true