stages:
  fill_na:
      cmd: python scripts/data_scripts/fill_na.py data/raw/SF_Mandarin_dataset_ver3_csv.csv
      deps:
        - data/raw/SF_Mandarin_dataset_ver3_csv.csv
        - scripts/data_scripts/fill_na.py
        - scripts/data_scripts/data_methods.py
      outs:
        - data/stage_fill_na

  data_prepare:
    cmd: python scripts/data_scripts/data_prepare.py data/stage_fill_na/dataset.csv
    deps:
      - data/stage_fill_na/dataset.csv
      - scripts/data_scripts/data_prepare.py
      - scripts/data_scripts/data_methods.py
    outs:
      - data/stage_data_prepare

  fix_errors:
    cmd: python scripts/data_scripts/fix_errors.py data/stage_data_prepare/dataset.csv
    deps:
      - data/stage_data_prepare/dataset.csv
      - scripts/data_scripts/fix_errors.py
      - scripts/data_scripts/data_methods.py
      - scripts/data_scripts/utils/seniority_cats.py
    outs:
      - data/stage_fix_errors

  create_features:
    cmd: python scripts/data_scripts/create_features.py data/stage_fix_errors/dataset.csv
    deps:
    - data/stage_fix_errors/dataset.csv
    - scripts/data_scripts/create_features.py
    - scripts/data_scripts/data_methods.py
    - scripts/data_scripts/utils/seniority_cats.py
    outs:
    - data/stage_create_features
#
#  train_test_split:
#    cmd: python scripts/data_scripts/train_test_split.py data/stage_create_features/dataset.csv
#    deps:
#    - data/stage_create_features/dataset.csv
#    - scripts/data_scripts/train_test_split.py
#    params:
#    - split.split_ratio
#    - split.bank_id_list
#    outs:
#    - data/stage_train_test_split

#  train_test_split:
#    cmd: python scripts/data_scripts/train_test_split.py data/stage_create_features/dataset.csv
#    deps:
#    - data/stage_create_features/dataset.csv
#    - scripts/data_scripts/train_test_split.py
#    params:
#    - split.split_ratio
#    - split.bank_id_list
#    outs:
#    - data/stage_train_test_split

  train:
    cmd: python scripts/model_scripts/${general.train_method}.py data/stage_train_test_split/train_${bank.bank_id}.csv
    deps:
      - data/stage_train_test_split/train_${bank.bank_id}.csv
      - scripts/model_scripts/${general.train_method}.py
    params:
      - general.train_method
      - general.bank_id
      - tree.max_depth
      - tree.n_estimators
      - log_reg.max_depth
      - neural.max_depth
      - neural.learning_rate_init
      - neural.verbose
      - neural.hidden_layer_sizes_x
      - neural.hidden_layer_sizes_y
    outs:
      - models/model_${general.train_method}.pkl

    evaluate:
      cmd: python scripts/model_scripts/evaluate.py data/stage_train_test_split/test_${bank.bank_id}.csv models/model_${general.train_method}_${bank.bank_id}.pkl score_${general.train_method}_${bank.bank_id}.json
      deps:
        - data/stage_train_test_split/test_${bank.bank_id}.csv
        - models/model_${bank.bank_id}.pkl
        - scripts/model_scripts/evaluate.py
      params:
        - general.bank_id
        - general.train_method
      metrics:
        - evaluate/score_${general.train_method}_${bank.bank_id}.json:
            cache: true