split:
  split_ratio: 0.3

general:
  bank_id: A
  train_method: dt

tree:
  max_depth: 4
  n_estimators: 100

log_reg:
  max_depth: 5

neural:
  max_depth: 1000
  learning_rate_init: 0.005
  verbose: True
  hidden_layer_sizes_x: 6
  hidden_layer_sizes_y: 2