split:
  split_ratio: 0.3
  random_state: 45

general:
  bank_id: B
  train_method: dt

tree:
  max_depth: 4
  n_estimators: 100
  eta: 0.2
  reg_lambda: 1
  reg_alpha: 1
  scale_pos_weight: 1

log_reg:
  max_depth: 5

neural:
  max_depth: 1000
  learning_rate_init: 0.005
  verbose: True
  hidden_layer_sizes_x: 6
  hidden_layer_sizes_y: 2