split:
  split_ratio: 0.3
  bank_id: A

bank:
  bank_id: A

tree:
  max_depth: 4

log_reg:
  max_depth: 5
  treshold : 0.75

neural:
  max_depth: 1000
  learning_rate_init: 0.005
  verbose: True
  hidden_layer_sizes_x: 6
  hidden_layer_sizes_y: 2